[package]
name = "rust-jellyfish"
version = "0.1.0"
authors = ["James Turk <dev@jamesturk.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "*"

[dev-dependencies]
csv = "1.1"
